// <auto-generated />
using ClasseStudente.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClasseStudente.Migrations
{
    [DbContext(typeof(StudClassContext))]
    [Migration("20251118093917_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("ClasseStudente.Model.Classe", b =>
                {
                    b.Property<int>("ClasseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Superficie")
                        .HasColumnType("INTEGER");

                    b.HasKey("ClasseId");

                    b.ToTable("Classe");
                });

            modelBuilder.Entity("ClasseStudente.Model.Studente", b =>
                {
                    b.Property<int>("Matricola")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FKClasse")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Matricola");

                    b.HasIndex("FKClasse");

                    b.ToTable("Studente");
                });

            modelBuilder.Entity("ClasseStudente.Model.Studente", b =>
                {
                    b.HasOne("ClasseStudente.Model.Classe", "Classe")
                        .WithMany("Studenti")
                        .HasForeignKey("FKClasse")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classe");
                });

            modelBuilder.Entity("ClasseStudente.Model.Classe", b =>
                {
                    b.Navigation("Studenti");
                });
#pragma warning restore 612, 618
        }
    }
}
