// <auto-generated />
using System;
using ES_sqlit.data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ES_sqlit.Migrations
{
    [DbContext(typeof(LibreriaContext))]
    partial class LibreriaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("ES_sqlit.model.Autore", b =>
                {
                    b.Property<int>("AutoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DataNascita")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AutoreId");

                    b.ToTable("Autori");
                });

            modelBuilder.Entity("ES_sqlit.model.Libro", b =>
                {
                    b.Property<int>("LibroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Anno")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AutoreId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Pagine")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titolo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LibroId");

                    b.HasIndex("AutoreId");

                    b.ToTable("Libri");
                });

            modelBuilder.Entity("ES_sqlit.model.Libro", b =>
                {
                    b.HasOne("ES_sqlit.model.Autore", "autore")
                        .WithMany("ListaLibri")
                        .HasForeignKey("AutoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("autore");
                });

            modelBuilder.Entity("ES_sqlit.model.Autore", b =>
                {
                    b.Navigation("ListaLibri");
                });
#pragma warning restore 612, 618
        }
    }
}
